// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk_rN6Ad-Fgt3kQOulbKwgnSYGqKLRpxU',
    appId: '1:881622223685:web:be7f6074a0c18e5fd50c2c',
    messagingSenderId: '881622223685',
    projectId: 'queue-df564',
    authDomain: 'queue-df564.firebaseapp.com',
    storageBucket: 'queue-df564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdPOn5wpPx8lstKlO6f8US1x8qCsUwS2k',
    appId: '1:881622223685:android:10edae38f526978cd50c2c',
    messagingSenderId: '881622223685',
    projectId: 'queue-df564',
    storageBucket: 'queue-df564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLd5h4HBb7O5DssXD_eBHCyWmI_A1kWE',
    appId: '1:881622223685:ios:41c99fdc35669f7dd50c2c',
    messagingSenderId: '881622223685',
    projectId: 'queue-df564',
    storageBucket: 'queue-df564.appspot.com',
    iosClientId: '881622223685-q5jnue7metf5duaurt4qbqivh5ap9852.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQueue',
  );
}
